// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package de.gzockoll.selenium.util;

public class EnvironmentBuilder extends
		EnvironmentBuilderBase<EnvironmentBuilder> {
	public static EnvironmentBuilder environment() {
		return new EnvironmentBuilder();
	}

	public EnvironmentBuilder() {
		super(new Environment());
	}

	public Environment build() {
		return getInstance();
	}
}

class EnvironmentBuilderBase<GeneratorT extends EnvironmentBuilderBase<GeneratorT>> {
	private Environment instance;

	protected EnvironmentBuilderBase(Environment aInstance) {
		instance = aInstance;
	}

	protected Environment getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAdminUrl(String aValue) {
		instance.setAdminUrl(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPmiUrl(String aValue) {
		instance.setPmiUrl(aValue);

		return (GeneratorT) this;
	}
}
